# Pandas DataFrames Workout

https://www.w3resource.com/python-exercises/pandas/index-dataframe.php

1. Write a Pandas program to create a dataframe from a dictionary and display it.

Sample data:
```
{'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
```

In [1]:
import pandas as pd
import numpy as np

a = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})
print(a)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

Sample Python dictionary data and list labels:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```


In [2]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

a = pd.DataFrame(data=exam_data, index=labels)
print(a)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


3. Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.

Sample Python dictionary data and list labels:

```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [7]:
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


4. Write a Pandas program to get the first 3 rows of a given DataFrame.

Sample Python dictionary data and list labels:
```
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [11]:
# print(a.head(3))
print(a.iloc[:3])

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


5. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [13]:
# b = pd.DataFrame(data=a, columns=['name', 'score'])
b = a[['name', 'score']]
print(b)

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


6. Write a Pandas program to select the specified columns and rows from a given data frame.
7. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.
8. Write a Pandas program to count the number of rows and columns of a DataFrame.
9. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.
10. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

In [30]:
# 6
b = a.iloc[[1,3,5,6],[1, 3]].iloc[:3]
print(b)

# 7
b = a[a['attempts'] > 2]
print(b)

# 8
print("rows: {}".format(len(a.axes[0])))
print("columns: {}".format(len(a.axes[1])))

# 9
b = a[a['score'].isnull()]
print(b)

# 10
b = a[a['score'].between(15,20)]
print(b)


   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes
rows: 10
columns: 4
    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


11. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.
12. Write a Pandas program to change the score in row 'd' to 11.5.
13. Write a Pandas program to calculate the sum of the examination attempts by the students.
14. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.
15. Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame. Values for each column will be: 
```
{ name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k" }
```

In [34]:
# 11
# b = a[a['attempts'] < 2]
# c = b[b['score'] > 15]
c = a[(a['attempts'] < 2) & (a['score'] > 15)]
print(c)

# 12
b = a.copy()
# b.at['d', 'score'] = 11.5
b.loc['d', 'score'] = 11.5
print(b)

# 13
c = a['attempts'].sum()
print(c)

# 14
d = a['score'].mean()
print(d)

# 15
b = a.copy()
# row = { 'name' : "Suresh", 'score': 15.5, 'attempts': 1, 'qualify': "yes"}
# b = pd.concat([a, pd.DataFrame([row], index=['k'])])

b.loc['k'] = ['Suresh', 15.5, 1, 'yes',]
print(b)

b = b.drop('k')
print(b)


    name  score  attempts qualify
j  Jonas   19.0         1     yes
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
19
13.5625
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes
        name  score  attempts qualify
a  Anasta

16. Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.
17. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.
18. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame. 
19. Write a Pandas program to delete the 'attempts' column from the DataFrame.
20. Write a Pandas program to insert a new column in existing DataFrame. 

In [30]:
#16
b = a.copy()
b = b.sort_values(by=['name', 'score'], ascending=[False, True])
print("#16:")
print(b)

#17
b = a.copy()
# b = b.replace('yes', True)
# b = b.replace('no', False)
b['qualify'] = b['qualify'].map({'yes': True, 'no': False})
print("#17:")
print(b)

#18
b = a.copy()
b['name'] = b['name'].replace('James', 'Suresh')
print("#18:")
print(b)

#19
b = a.copy()
# b = b.drop(['attempts'], axis=1)
b.pop('attempts')
print("#19:")
print(b)

#20
color = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red']
b = a.copy()
b['color'] = color
print("#20:")
print(b)

#16:
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes
#17:
        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True
#18:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5     

21. Write a Pandas program to iterate over rows in a DataFrame.

Sample Python dictionary data and list labels:
```
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
```

22. Write a Pandas program to get list from DataFrame column headers.
23. Write a Pandas program to rename columns of a given DataFrame 
24. Write a Pandas program to select rows from a given DataFrame based on values in some columns.
25. Write a Pandas program to change the order of a DataFrame columns.

26. Write a Pandas program to add one row in an existing DataFrame.
27. Write a Pandas program to write a DataFrame to CSV file using tab separator.
28. Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).
29. Write a Pandas program to delete DataFrame row(s) based on given column value.
30. Write a Pandas program to widen output display to see more columns.

In [ ]:
# 26
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df2 = {'col1': 10, 'col2': 11, 'col3': 12}

# 27
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

# 28
df1 = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})

# 29
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

# 30
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

31. Write a Pandas program to select a row of series/dataframe by given integer index. (i=2)
32. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe.
33. Write a Pandas program to convert index in a column of the given dataframe.
34. Write a Pandas program to set a given value for particular cell in DataFrame using index value. (Set Kevin to 10.2)
35. Write a Pandas program to count the NaN values in one or more columns in DataFrame.

In [ ]:
# 31
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

# 32
# use a

# 33
# use a

# 34
# use a

# 35
# use a